# ---
# include:
#   - board: nice_nano_v2
#     shield: corne_left nice_view_adapter nice_view
#   - board: nice_nano_v2
#     shield: corne_right nice_view_adapter nice_view

# This file generates the GitHub Actions matrix
---
include:
  - board: nice_nano
    shield: corne_left nice_view_adapter nice_view
  - board: nice_nano
    shield: corne_right nice_view_adapter nice_view
